### PR TITLE
disallow manual trigger of completed tasks

### LINKED ISSUE #92: manually trigger a completed workflow should failed
if a workflow is done, manually trigger it should failed.

if a workflow is completed, any queue run shoud also failed to run

### PR DESCRIPTION
**Pull request by v9n**
Fixes #92

### CODE REVIEW

File: model/task.go [hunk 1]
```diff
@@ -130,6 +130,18 @@ func (t *Task) OwnedBy(address common.Address) bool {
 	return strings.EqualFold(t.Owner, address.Hex())
 }
 
+// A task is runable when both of these condition are matched
+//  1. Its max execution has not reached
+//  2. Its expiration time has not reached
+func (t *Task) Runable() bool {
```
Comment (chrisli30) [inline model/task.go:136]: I’m not sure about the naming in go, but to be consistent with the name `TaskIsNotRunable`, I’d call this function `isRunnable()`. The `is` will clearly indicate that this is boolean returning function.

**Review by chrisli30 — APPROVED** [review]
Looks good, I left one minor comment.

File: model/task.go (hunk 1 above)
Comment (chrisli30) [reply model/task.go]: Yeah, understood and sounds good!

**Review by chrisli30 — APPROVED** [review]
